Update

diff --git a/.github/workflows/maven-workflow-run.yml b/.github/workflows/maven-workflow-run.yml
--- a/.github/workflows/maven-workflow-run.yml
+++ b/.github/workflows/maven-workflow-run.yml
@@ -53,24 +53,30 @@ jobs:
           echo "export PATH=\$PATH:\$ANDROID_HOME/tools" >> $GITHUB_ENV
           echo "export PATH=\$PATH:\$ANDROID_HOME/tools/bin" >> $GITHUB_ENV
 
-      # 9. Tạo Android Emulator
+      # 9. Kiểm tra xem emulator có trong PATH không
+      - name: Check Emulator Path
+        run: |
+          echo "Checking if emulator is in PATH"
+          which emulator || echo "Emulator not found in PATH"
+
+      # 10. Tạo Android Emulator
       - name: Create Android Emulator
         run: |
           echo "no" | avdmanager create avd --name test_emulator --package "system-images;android-30;google_apis;x86_64"
 
-      # 10. Khởi động Android Emulator
+      # 11. Khởi động Android Emulator
       - name: Start Android Emulator
         run: |
           emulator -avd test_emulator -no-window -gpu off -qemu -m 2048 -enable-kvm & 
           sleep 180  # Đợi emulator khởi động
 
-      # 11. Kiểm tra trạng thái của Emulator
+      # 12. Kiểm tra trạng thái của Emulator
       - name: Check Emulator Status
         run: |
           adb wait-for-device
           adb devices || (echo "Emulator is not running." && exit 1)
 
-      # 12. Dừng Appium Server nếu đang chạy
+      # 13. Dừng Appium Server nếu đang chạy
       - name: Stop Appium Server if running
         run: |
           if pgrep -f appium; then
@@ -78,13 +84,13 @@ jobs:
             pkill -f appium
           fi
 
-      # 13. Khởi động Appium Server trên cổng khác (ví dụ: 4726)
+      # 14. Khởi động Appium Server trên cổng khác (ví dụ: 4726)
       - name: Start Appium Server
         run: |
           appium -p 4726 | tee appium.log &  # Khởi động Appium server trên cổng 4726 và ghi log
           sleep 30  # Đợi một chút để server khởi động
 
-      # 14. Kiểm tra trạng thái của Appium server
+      # 15. Kiểm tra trạng thái của Appium server
       - name: Check Appium Server Status
         run: |
           sleep 5  # Đợi một chút trước khi kiểm tra
@@ -96,13 +102,13 @@ jobs:
             exit 1
           fi
 
-      # 15. Chạy các bài kiểm tra Appium
+      # 16. Chạy các bài kiểm tra Appium
       - name: Run Appium tests
         run: |
           cd android/testng-examples  # Đảm bảo bạn đang ở đúng thư mục
           mvn clean test -Dappium.server=http://localhost:4726/wd/hub  # Sử dụng cổng 4726
 
-      # 16. Dọn dẹp sau khi test xong
+      # 17. Dọn dẹp sau khi test xong
       - name: Stop Emulator
         run: |
           adb -s emulator-5554 emu kill
